### ISSUE TITLE
Unsupported param in genenis.json

### ISSUE THREAD

**Issue by davide-perego-commercio** [commercionetwork/chains#17]
Starting a new node from scratch, the application crashes reading the genesis.json indicating that a field "max_wasm_code_size" is unknown
Removing the item from file, the daemon starts without problems.

```
11:05PM INF asserting crisis invariants inv=10/11 module=x/crisis name=distribution/module-account
11:05PM INF asserting crisis invariants inv=11/11 module=x/crisis name=gov/module-account
11:05PM INF asserted all invariants duration=146.379372 height=2233554 module=x/crisis
11:05PM INF created new capability module=ibc name=ports/transfer
11:05PM INF port binded module=x/ibc/port port=transfer
11:05PM INF claimed capability capability=1 module=transfer name=ports/transfer
panic: unknown field "max_wasm_code_size" in types.Params

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x0?, {0xc00022c1a0?, 0x28797d0?, 0xc0010d3ce0?}, {0x285e260?, 0xc006ca2080?})
	github.com/cosmos/cosmos-sdk@v0.45.11/codec/proto_codec.go:178 +0x45
github.com/CosmWasm/wasmd/x/wasm.AppModule.InitGenesis({{}, {_, _}, _, {_, _}, {_, _}, {_, _}}, ...)
	github.com/CosmWasm/wasmd@v0.27.0/x/wasm/module.go:161 +0xc2
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x2870220, 0xc00012c000}, {0x287fe60, 0xc000024880}, {{0x0, 0x0}, {0xc0013b40e0, 0xb}, 0x2214d2, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.11/types/module/module.go:327 +0x29d
github.com/commercionetwork/commercionetwork/app.(*App).InitChainer(_, {{0x2870220, 0xc00012c000}, {0x287fe60, 0xc000024880}, {{0x0, 0x0}, {0xc0013b40e0, 0xb}, 0x2214d2, ...}, ...}, ...)
	github.com/commercionetwork/commercionetwork/app/app.go:933 +0x20e
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000420380, {{0x0, 0xed7eab600, 0x0}, {0xc0013b40e0, 0xb}, 0xc000deea60, {0xc000e37500, 0x47, 0x47}, ...})
	github.com/cosmos/cosmos-sdk@v0.45.11/baseapp/abci.go:63 +0x455
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000e886c0, {{0x0, 0xed7eab600, 0x0}, {0xc0013b40e0, 0xb}, 0xc000deea60, {0xc000e37500, 0x47, 0x47}, ...})
	github.com/tendermint/tendermint@v0.34.23/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x0?, {{0x0, 0xed7eab600, 0x0}, {0xc0013b40e0, 0xb}, 0xc000deea60, {0xc000e37500, 0x47, 0x47}, ...})
	github.com/tendermint/tendermint@v0.34.23/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x284f6e0, 0x8}}, {0xc0013b40e0, 0xb}, 0x2214d2, 0x0, {{0x0, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.23/consensus/replay.go:319 +0xd78
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000fd9d90, {0x28808b0, 0xc001c040d0})
	github.com/tendermint/tendermint@v0.34.23/consensus/replay.go:268 +0x3d4
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x284f6e0, 0x8}}, {0xc0013b40e0, 0xb}, 0x2214d2, 0x0, ...}, ...)
	github.com/tendermint/tendermint@v0.34.23/node/node.go:329 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000dc28c0, {0x286cea0, 0xc000d11720}, 0xc001c08810, {0x2856860, 0xc000012ab0}, 0x0?, 0x0?, 0xc001c08a20, {0x28713d8, ...}, ...)
	github.com/tendermint/tendermint@v0.34.23/node/node.go:777 +0x597
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x288bce8, 0xc000d13980}, {0x0, 0x0}, {0x2875b98, 0xc000e828c0}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.11/server/start.go:280 +0x7db
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000fe6f00?, {0x3737130?, 0x0?, 0x0?})
	github.com/cosmos/cosmos-sdk@v0.45.11/server/start.go:128 +0x169
github.com/spf13/cobra.(*Command).execute(0xc000fe6f00, {0x3737130, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.0/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001b9500)
	github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.0/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.6.0/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc00014ee28, 0x17})
	github.com/cosmos/cosmos-sdk@v0.45.11/server/cmd/execute.go:36 +0x1eb
main.main()
	github.com/commercionetwork/commercionetwork/cmd/commercionetworkd/main.go:13 +0x2c

```

**Comment by marcotradenet** [comment]
You cannot activate a node with the current software version from genesis.     
One of the dumps at https://quicksync.commercio.network or the state sync procedure must be used.
If you want to start from genesis you have to use a special procedure, using the older versions of the software.    
We will try to publish the complete procedure in the future.
